services:
  app:
    image: ghcr.io/minderrx2-art/goprl:latest
    ports:
      - "80:80" # http
      - "443:443" # https
    environment:
      - DATABASE_URL=postgres://user:${DB_PASSWORD}@db:5432/goprl?sslmode=disable
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - BASE_URL=http://${PUBLIC_IP}
      - RATE_LIMIT=${RATE_LIMIT}
      - PORT=${PORT}
      - ENV=${ENV}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    logging:
      driver: gcplogs
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=goprl
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d goprl" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
